baseURL = 'https://ok300.github.io/abc-prague-hugo/'
languageCode = 'en-us'
title = 'ABC Prague Hugo'
disableKinds = ['taxonomy', 'term']

[params]
  description = 'A sample Hugo blog'

[markup.goldmark.renderer]
  unsafe = true
